// ===== SOLLER MARKETPLACE - DATABASE =====
// Casting Exclusivo Soller - 48 Influenciadores Verificados

const influencers = [
    // ===== FASHION & LIFESTYLE =====
    {
        id: 1,
        name: 'Aline Marquez',
        handle: '@alinemarquez',
        followers: '274K',
        followers_instagram: 265000,
        followers_tiktok: 9000,
        engagement: 2.1,
        engagement_instagram: 2.2,
        engagement_tiktok: 1.8,
        categories: ['Fashion', 'Lifestyle'],
        subcategories: ['Streetwear', 'Moda Feminina', 'Tendências'],
        score: 88,
        sollerExclusive: true,
        trending: false,
        avgROI: 4.2,
        price: 6000,
        growth: 3.5,
        audienceQuality: 89,
        contentScore: 87,
        avatar: '👗',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português', 'Inglês'],
        bestPostTime: '19h-21h',
        audienceGender: { female: 78, male: 22 },
        audienceAge: { '18-24': 35, '25-34': 45, '35-44': 15, '45+': 5 },
        brandCollabs: ['Zara', 'C&A', 'Renner'],
        specialties: ['Lookbooks', 'Fashion Week', 'Street Style'],
        platforms: ['Instagram', 'TikTok'],
        bio: 'Seu guia definitivo para o estilo urbano e as últimas tendências'
    },
    {
        id: 2,
        name: 'Bruna Hamú',
        handle: '@brunahamu',
        followers: '3.626M',
        followers_instagram: 3500000,
        followers_tiktok: 126000,
        engagement: 0.8,
        engagement_instagram: 0.8,
        engagement_tiktok: 1.2,
        categories: ['Lifestyle', 'Travel', 'Wellness'],
        subcategories: ['Viagens', 'Gastronomia', 'Bem-estar'],
        score: 87,
        sollerExclusive: true,
        trending: false,
        avgROI: 3.8,
        price: 35000,
        growth: 1.2,
        audienceQuality: 86,
        contentScore: 88,
        avatar: '✨',
        verified: true,
        location: 'Rio de Janeiro, RJ',
        languages: ['Português'],
        bestPostTime: '12h-14h',
        audienceGender: { female: 72, male: 28 },
        audienceAge: { '18-24': 28, '25-34': 42, '35-44': 20, '45+': 10 },
        brandCollabs: ['Natura', 'Nike', 'Samsung'],
        specialties: ['Travel Content', 'Product Placement', 'Brand Storytelling'],
        platforms: ['Instagram', 'TikTok'],
        bio: 'Conteúdo que inspira viagens, bem-estar e uma vida mais leve'
    },
    {
        id: 3,
        name: 'Camila Dias',
        handle: '@bycamiladias',
        followers: '1.925M',
        followers_instagram: 1300000,
        followers_tiktok: 625000,
        engagement: 1.9,
        engagement_instagram: 1.8,
        engagement_tiktok: 2.1,
        categories: ['Home Decor', 'Lifestyle'],
        subcategories: ['Decoração', 'DIY', 'Organização'],
        score: 89,
        sollerExclusive: true,
        trending: true,
        avgROI: 4.3,
        price: 20000,
        growth: 4.2,
        audienceQuality: 90,
        contentScore: 88,
        avatar: '🏠',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português', 'Espanhol'],
        bestPostTime: '10h-12h',
        audienceGender: { female: 85, male: 15 },
        audienceAge: { '18-24': 22, '25-34': 48, '35-44': 25, '45+': 5 },
        brandCollabs: ['Tok&Stok', 'Leroy Merlin', 'MadeiraMadeira'],
        specialties: ['Home Decor', 'DIY Tutorials', 'Organization Tips'],
        platforms: ['Instagram', 'TikTok', 'YouTube'],
        bio: 'Dicas e tutoriais para transformar qualquer espaço com criatividade'
    },
    {
        id: 4,
        name: 'Camila Monteiro',
        handle: '@camilamonteiro',
        followers: '3.683M',
        followers_instagram: 3300000,
        followers_tiktok: 383000,
        engagement: 1.84,
        engagement_instagram: 1.9,
        engagement_tiktok: 1.5,
        categories: ['Body Positive', 'Fashion', 'Lifestyle'],
        subcategories: ['Moda Plus Size', 'Autoestima', 'Empoderamento'],
        score: 91,
        sollerExclusive: true,
        trending: true,
        avgROI: 4.6,
        price: 40000,
        growth: 5.8,
        audienceQuality: 92,
        contentScore: 90,
        avatar: '💪',
        verified: true,
        location: 'Belo Horizonte, MG',
        languages: ['Português'],
        bestPostTime: '20h-22h',
        audienceGender: { female: 88, male: 12 },
        audienceAge: { '18-24': 30, '25-34': 40, '35-44': 22, '45+': 8 },
        brandCollabs: ['C&A', 'Riachuelo', 'Avon'],
        specialties: ['Body Positivity', 'Fashion Inclusiva', 'Self-Love Content'],
        platforms: ['Instagram', 'TikTok', 'YouTube'],
        bio: 'Empoderando corpos e mentes através da moda e do autocuidado'
    },
    {
        id: 5,
        name: 'Camila Nereu',
        handle: '@camilanereu',
        followers: '476K',
        followers_instagram: 321000,
        followers_tiktok: 155000,
        engagement: 3.8,
        engagement_instagram: 3.5,
        engagement_tiktok: 4.2,
        categories: ['Fashion', 'Business'],
        subcategories: ['Alta Costura', 'Fashion Business', 'Tendências'],
        score: 90,
        sollerExclusive: true,
        trending: false,
        avgROI: 4.5,
        price: 8500,
        growth: 6.3,
        audienceQuality: 91,
        contentScore: 89,
        avatar: '👠',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português', 'Inglês', 'Francês'],
        bestPostTime: '18h-20h',
        audienceGender: { female: 82, male: 18 },
        audienceAge: { '18-24': 25, '25-34': 50, '35-44': 20, '45+': 5 },
        brandCollabs: ['Dior', 'Chanel', 'Louis Vuitton'],
        specialties: ['Luxury Fashion', 'Fashion Week Coverage', 'Trend Analysis'],
        platforms: ['Instagram', 'TikTok'],
        bio: 'Análise aprofundada do universo da alta costura e do fashion business'
    },

    // ===== BEAUTY & WELLNESS =====
    {
        id: 6,
        name: 'Duda Guerra',
        handle: '@dudaa.guerra',
        followers: '1.344M',
        followers_instagram: 954000,
        followers_tiktok: 390000,
        engagement: 3.2,
        engagement_instagram: 3.0,
        engagement_tiktok: 3.5,
        categories: ['Beauty', 'Skincare'],
        subcategories: ['Maquiagem', 'Skincare', 'Tutoriais'],
        score: 91,
        sollerExclusive: true,
        trending: true,
        avgROI: 4.7,
        price: 15000,
        growth: 12.3,
        audienceQuality: 92,
        contentScore: 90,
        avatar: '💄',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português'],
        bestPostTime: '15h-17h',
        audienceGender: { female: 92, male: 8 },
        audienceAge: { '18-24': 45, '25-34': 35, '35-44': 15, '45+': 5 },
        brandCollabs: ['MAC', 'Sephora', 'O Boticário'],
        specialties: ['Makeup Tutorials', 'Product Reviews', 'Beauty Trends'],
        platforms: ['Instagram', 'TikTok', 'YouTube'],
        bio: 'Tutoriais de maquiagem e dicas de beleza que você precisa saber'
    },
    {
        id: 7,
        name: 'Gabriela Sobral',
        handle: '@gabrielasobral',
        followers: '2.93M',
        followers_instagram: 665000,
        followers_tiktok: 2300000,
        engagement: 4.2,
        engagement_instagram: 2.8,
        engagement_tiktok: 5.1,
        categories: ['Beauty', 'Skincare', 'Wellness'],
        subcategories: ['Skincare Coreana', 'Rotina de Beleza', 'Anti-aging'],
        score: 93,
        sollerExclusive: true,
        trending: true,
        avgROI: 5.2,
        price: 28000,
        growth: 18.5,
        audienceQuality: 94,
        contentScore: 92,
        avatar: '🌸',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português', 'Inglês'],
        bestPostTime: '21h-23h',
        audienceGender: { female: 89, male: 11 },
        audienceAge: { '18-24': 38, '25-34': 42, '35-44': 15, '45+': 5 },
        brandCollabs: ['La Roche-Posay', 'Vichy', 'ISDIN'],
        specialties: ['K-Beauty', 'Skincare Science', 'Product Testing'],
        platforms: ['TikTok', 'Instagram', 'YouTube'],
        bio: 'Desvendando os segredos da pele perfeita com ciência e K-Beauty'
    },
    {
        id: 8,
        name: 'Nina Rocha',
        handle: '@ninarochakanner',
        followers: '464K',
        followers_instagram: 17000,
        followers_tiktok: 447000,
        engagement: 4.5,
        engagement_instagram: 3.8,
        engagement_tiktok: 4.8,
        categories: ['Beauty', 'Art'],
        subcategories: ['Maquiagem Artística', 'Transformações', 'Trends'],
        score: 92,
        sollerExclusive: true,
        trending: true,
        avgROI: 5.0,
        price: 9500,
        growth: 12.5,
        audienceQuality: 93,
        contentScore: 91,
        avatar: '🎨',
        verified: true,
        location: 'Rio de Janeiro, RJ',
        languages: ['Português'],
        bestPostTime: '19h-21h',
        audienceGender: { female: 87, male: 13 },
        audienceAge: { '18-24': 52, '25-34': 33, '35-44': 12, '45+': 3 },
        brandCollabs: ['NYX', 'Ruby Rose', 'Vult'],
        specialties: ['Creative Makeup', 'TikTok Trends', 'Viral Content'],
        platforms: ['TikTok', 'Instagram'],
        bio: 'Onde maquiagem se encontra com a arte. Transformações criativas e virais'
    },
    {
        id: 9,
        name: 'Stephanie Garcia',
        handle: '@stephaniezgarcia',
        followers: '115K',
        followers_instagram: 115000,
        followers_tiktok: 0,
        engagement: 3.5,
        engagement_instagram: 3.5,
        engagement_tiktok: 0,
        categories: ['Beauty', 'Wellness', 'Sustainability'],
        subcategories: ['Clean Beauty', 'Sustentável', 'Vegano'],
        score: 89,
        sollerExclusive: true,
        trending: false,
        avgROI: 4.6,
        price: 2600,
        growth: 5.8,
        audienceQuality: 90,
        contentScore: 88,
        avatar: '🌿',
        verified: true,
        location: 'Curitiba, PR',
        languages: ['Português', 'Inglês'],
        bestPostTime: '11h-13h',
        audienceGender: { female: 91, male: 9 },
        audienceAge: { '18-24': 28, '25-34': 45, '35-44': 22, '45+': 5 },
        brandCollabs: ['Simple Organic', 'Bioré', 'Cativa'],
        specialties: ['Clean Beauty', 'Eco-friendly Products', 'Natural Skincare'],
        platforms: ['Instagram'],
        bio: 'Beleza consciente e sustentável, cuidando de você e do planeta'
    },

    // ===== FITNESS & WELLNESS =====
    {
        id: 10,
        name: 'Carol Peixinho',
        handle: '@carolpeixinho',
        followers: '6.392M',
        followers_instagram: 5500000,
        followers_tiktok: 892000,
        engagement: 0.86,
        engagement_instagram: 0.9,
        engagement_tiktok: 0.7,
        categories: ['Fitness', 'Lifestyle'],
        subcategories: ['Treinos', 'Nutrição', 'Lifestyle Fitness'],
        score: 88,
        sollerExclusive: true,
        trending: false,
        avgROI: 3.9,
        price: 45000,
        growth: 1.5,
        audienceQuality: 87,
        contentScore: 89,
        avatar: '🏃‍♀️',
        verified: true,
        location: 'Salvador, BA',
        languages: ['Português'],
        bestPostTime: '6h-8h',
        audienceGender: { female: 68, male: 32 },
        audienceAge: { '18-24': 25, '25-34': 45, '35-44': 22, '45+': 8 },
        brandCollabs: ['Nike', 'Adidas', 'Growth'],
        specialties: ['Workout Routines', 'Healthy Lifestyle', 'Motivation'],
        platforms: ['Instagram', 'TikTok'],
        bio: 'Inspirando uma vida ativa e saudável com treinos e nutrição'
    },
    {
        id: 11,
        name: 'Gabriela Muniz',
        handle: '@gabrielamunizdiniz',
        followers: '37K',
        followers_instagram: 34500,
        followers_tiktok: 2500,
        engagement: 3.8,
        engagement_instagram: 3.6,
        engagement_tiktok: 4.5,
        categories: ['Fitness', 'Wellness'],
        subcategories: ['Yoga', 'Pilates', 'Mindfulness'],
        score: 88,
        sollerExclusive: true,
        trending: false,
        avgROI: 4.6,
        price: 1500,
        growth: 7.2,
        audienceQuality: 89,
        contentScore: 87,
        avatar: '🧘‍♀️',
        verified: true,
        location: 'Florianópolis, SC',
        languages: ['Português', 'Inglês'],
        bestPostTime: '7h-9h',
        audienceGender: { female: 82, male: 18 },
        audienceAge: { '18-24': 20, '25-34': 48, '35-44': 25, '45+': 7 },
        brandCollabs: ['Lululemon', 'Track&Field', 'Bio Ritmo'],
        specialties: ['Yoga Practice', 'Meditation', 'Wellness Tips'],
        platforms: ['Instagram', 'TikTok'],
        bio: 'Mindfulness e movimento para uma vida mais equilibrada'
    },
    {
        id: 12,
        name: 'Vera Minelli',
        handle: '@veraminelli',
        followers: '149K',
        followers_instagram: 149000,
        followers_tiktok: 0,
        engagement: 1.48,
        engagement_instagram: 1.48,
        engagement_tiktok: 0,
        categories: ['Fitness', 'Nutrition'],
        subcategories: ['CrossFit', 'Nutrição Esportiva', 'Competições'],
        score: 86,
        sollerExclusive: true,
        trending: false,
        avgROI: 3.8,
        price: 3200,
        growth: 1.8,
        audienceQuality: 85,
        contentScore: 87,
        avatar: '💪',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português'],
        bestPostTime: '5h-7h',
        audienceGender: { female: 55, male: 45 },
        audienceAge: { '18-24': 30, '25-34': 42, '35-44': 20, '45+': 8 },
        brandCollabs: ['Reebok', 'Optimum', 'Max Titanium'],
        specialties: ['CrossFit Training', 'Competition Prep', 'Sports Nutrition'],
        platforms: ['Instagram', 'YouTube'],
        bio: 'CrossFit e nutrição esportiva para performance e resultados'
    },
    {
        id: 13,
        name: 'Kim Zucatelli',
        handle: '@kimzucatelli',
        followers: '323.7K',
        followers_instagram: 291000,
        followers_tiktok: 32700,
        engagement: 2.8,
        engagement_instagram: 2.7,
        engagement_tiktok: 3.1,
        categories: ['Wellness', 'Food', 'Nutrition'],
        subcategories: ['Alimentação Saudável', 'Receitas Fit', 'Detox'],
        score: 89,
        sollerExclusive: true,
        trending: false,
        avgROI: 4.4,
        price: 7200,
        growth: 4.5,
        audienceQuality: 90,
        contentScore: 88,
        avatar: '🥗',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português', 'Inglês'],
        bestPostTime: '12h-14h',
        audienceGender: { female: 78, male: 22 },
        audienceAge: { '18-24': 22, '25-34': 46, '35-44': 25, '45+': 7 },
        brandCollabs: ['Jasmine', 'Mãe Terra', 'Native'],
        specialties: ['Healthy Recipes', 'Meal Prep', 'Nutrition Tips'],
        platforms: ['Instagram', 'TikTok', 'YouTube'],
        bio: 'Receitas saudáveis e dicas de nutrição para uma vida leve e saborosa'
    },
    {
        id: 14,
        name: 'Fernanda Kanner',
        handle: '@ferochakanner',
        followers: '131K',
        followers_instagram: 131000,
        followers_tiktok: 0,
        engagement: 1.8,
        engagement_instagram: 1.8,
        engagement_tiktok: 0,
        categories: ['Wellness', 'Mindfulness'],
        subcategories: ['Meditação', 'Terapias Holísticas', 'Autocuidado'],
        score: 87,
        sollerExclusive: true,
        trending: false,
        avgROI: 4.1,
        price: 2800,
        growth: 2.5,
        audienceQuality: 88,
        contentScore: 86,
        avatar: '🧘',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português'],
        bestPostTime: '20h-22h',
        audienceGender: { female: 85, male: 15 },
        audienceAge: { '18-24': 18, '25-34': 38, '35-44': 32, '45+': 12 },
        brandCollabs: ['Weleda', 'doTERRA', 'Lush'],
        specialties: ['Meditation Guides', 'Holistic Health', 'Self-Care Routines'],
        platforms: ['Instagram'],
        bio: 'Guias de meditação e práticas holísticas para o seu bem-estar diário'
    },

    // ===== BUSINESS & EDUCATION =====
    {
        id: 15,
        name: 'Isabela Soller',
        handle: '@isabelasoller',
        followers: '45.1K',
        followers_instagram: 45100,
        followers_tiktok: 0,
        engagement: 5.2,
        engagement_instagram: 5.2,
        engagement_tiktok: 0,
        categories: ['Business', 'Marketing', 'Entrepreneurship'],
        subcategories: ['Marketing Digital', 'Empreendedorismo', 'Influencer Marketing'],
        score: 91,
        sollerExclusive: true,
        trending: true,
        avgROI: 5.0,
        price: 2200,
        growth: 15.3,
        audienceQuality: 92,
        contentScore: 90,
        avatar: '💼',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português', 'Inglês', 'Espanhol'],
        bestPostTime: '9h-11h',
        audienceGender: { female: 62, male: 38 },
        audienceAge: { '18-24': 28, '25-34': 45, '35-44': 20, '45+': 7 },
        brandCollabs: ['LinkedIn', 'Hotmart', 'RD Station'],
        specialties: ['Digital Marketing', 'Business Strategy', 'Influencer Economy'],
        platforms: ['Instagram', 'LinkedIn'],
        bio: 'Marketing de influência e empreendedorismo na economia digital'
    },
    {
        id: 16,
        name: 'Martha Leonardis',
        handle: '@marthaleonardis',
        followers: '231.3K',
        followers_instagram: 221000,
        followers_tiktok: 10300,
        engagement: 2.3,
        engagement_instagram: 2.3,
        engagement_tiktok: 2.5,
        categories: ['Business', 'Finance'],
        subcategories: ['Finanças Pessoais', 'Investimentos', 'Educação Financeira'],
        score: 89,
        sollerExclusive: true,
        trending: true,
        avgROI: 4.5,
        price: 5200,
        growth: 5.2,
        audienceQuality: 90,
        contentScore: 88,
        avatar: '📊',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português', 'Inglês'],
        bestPostTime: '19h-21h',
        audienceGender: { female: 48, male: 52 },
        audienceAge: { '18-24': 22, '25-34': 48, '35-44': 22, '45+': 8 },
        brandCollabs: ['XP', 'Nubank', 'BTG Pactual'],
        specialties: ['Personal Finance', 'Investment Tips', 'Financial Education'],
        platforms: ['Instagram', 'TikTok', 'YouTube'],
        bio: 'Simplificando o mundo das finanças para te ajudar a investir melhor'
    },
    {
        id: 17,
        name: 'Rafaela Lamastra',
        handle: '@rafalamastra',
        followers: '149.6K',
        followers_instagram: 33300,
        followers_tiktok: 116300,
        engagement: 4.2,
        engagement_instagram: 3.5,
        engagement_tiktok: 4.8,
        categories: ['Business', 'Technology'],
        subcategories: ['Startup', 'Inovação', 'Tech Business'],
        score: 90,
        sollerExclusive: true,
        trending: true,
        avgROI: 4.8,
        price: 3500,
        growth: 9.5,
        audienceQuality: 91,
        contentScore: 89,
        avatar: '🚀',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português', 'Inglês'],
        bestPostTime: '18h-20h',
        audienceGender: { female: 45, male: 55 },
        audienceAge: { '18-24': 35, '25-34': 42, '35-44': 18, '45+': 5 },
        brandCollabs: ['Google', 'AWS', 'Startupbootcamp'],
        specialties: ['Startup Ecosystem', 'Innovation', 'Tech Entrepreneurship'],
        platforms: ['TikTok', 'Instagram', 'LinkedIn'],
        bio: 'Inovação e tecnologia na prática. Guia para o mundo das startups'
    },

    // ===== ENTERTAINMENT & ARTS =====
    {
        id: 18,
        name: 'Edson Celulari',
        handle: '@edsoncelulari',
        followers: '2.193M',
        followers_instagram: 2100000,
        followers_tiktok: 93000,
        engagement: 1.4,
        engagement_instagram: 1.4,
        engagement_tiktok: 1.2,
        categories: ['Entertainment', 'Art'],
        subcategories: ['Teatro', 'Cinema', 'TV'],
        score: 86,
        sollerExclusive: true,
        trending: false,
        avgROI: 3.7,
        price: 25000,
        growth: 0.8,
        audienceQuality: 85,
        contentScore: 87,
        avatar: '🎭',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português'],
        bestPostTime: '20h-22h',
        audienceGender: { female: 58, male: 42 },
        audienceAge: { '18-24': 15, '25-34': 30, '35-44': 35, '45+': 20 },
        brandCollabs: ['Globo', 'Netflix', 'Amazon Prime'],
        specialties: ['Acting', 'Theater', 'Cultural Content'],
        platforms: ['Instagram', 'TikTok'],
        bio: 'Um palco para a arte, cultura e os bastidores do entretenimento'
    },
    {
        id: 19,
        name: 'Paulo Vilhena',
        handle: '@vilhenap',
        followers: '953K',
        followers_instagram: 953000,
        followers_tiktok: 0,
        engagement: 1.5,
        engagement_instagram: 1.5,
        engagement_tiktok: 0,
        categories: ['Entertainment', 'Lifestyle', 'Sports'],
        subcategories: ['Esportes', 'Aventura', 'Lifestyle'],
        score: 86,
        sollerExclusive: true,
        trending: false,
        avgROI: 3.8,
        price: 18000,
        growth: 1.2,
        audienceQuality: 85,
        contentScore: 87,
        avatar: '🏄‍♂️',
        verified: true,
        location: 'Rio de Janeiro, RJ',
        languages: ['Português'],
        bestPostTime: '18h-20h',
        audienceGender: { female: 45, male: 55 },
        audienceAge: { '18-24': 20, '25-34': 35, '35-44': 30, '45+': 15 },
        brandCollabs: ['Red Bull', 'GoPro', 'Oakley'],
        specialties: ['Extreme Sports', 'Adventure Content', 'Lifestyle'],
        platforms: ['Instagram'],
        bio: 'Aventura, esportes e um lifestyle inspirador'
    },
    {
        id: 20,
        name: 'Munik Nunes',
        handle: '@muniknunes',
        followers: '12.188M',
        followers_instagram: 11500000,
        followers_tiktok: 688000,
        engagement: 1.2,
        engagement_instagram: 1.1,
        engagement_tiktok: 1.8,
        categories: ['Entertainment', 'Lifestyle'],
        subcategories: ['Reality TV', 'Música', 'Lifestyle'],
        score: 89,
        sollerExclusive: true,
        trending: false,
        avgROI: 3.5,
        price: 80000,
        growth: 1.5,
        audienceQuality: 86,
        contentScore: 88,
        avatar: '🌟',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português'],
        bestPostTime: '21h-23h',
        audienceGender: { female: 72, male: 28 },
        audienceAge: { '18-24': 42, '25-34': 35, '35-44': 18, '45+': 5 },
        brandCollabs: ['Spotify', 'Globo', 'Universal Music'],
        specialties: ['Entertainment', 'Music', 'TV Appearances'],
        platforms: ['Instagram', 'TikTok', 'YouTube'],
        bio: 'Acompanhando meu dia a dia no mundo da música e da TV'
    },
    {
        id: 21,
        name: 'Kika Simonsen',
        handle: '@kikasimonsenticoulat',
        followers: '144K',
        followers_instagram: 135000,
        followers_tiktok: 9000,
        engagement: 2.1,
        engagement_instagram: 2.2,
        engagement_tiktok: 1.8,
        categories: ['Art', 'Lifestyle'],
        subcategories: ['Arte Contemporânea', 'Curadoria', 'Galerias'],
        score: 88,
        sollerExclusive: true,
        trending: false,
        avgROI: 4.2,
        price: 3500,
        growth: 3.2,
        audienceQuality: 89,
        contentScore: 90,
        avatar: '🎨',
        verified: true,
        location: 'Rio de Janeiro, RJ',
        languages: ['Português', 'Inglês', 'Francês'],
        bestPostTime: '16h-18h',
        audienceGender: { female: 65, male: 35 },
        audienceAge: { '18-24': 18, '25-34': 38, '35-44': 28, '45+': 16 },
        brandCollabs: ['MASP', 'Pinacoteca', 'Christie\'s'],
        specialties: ['Contemporary Art', 'Art Curation', 'Gallery Events'],
        platforms: ['Instagram'],
        bio: 'Curadoria de arte contemporânea e uma visão única sobre a criatividade'
    },
    {
        id: 22,
        name: 'Fernanda Cintra',
        handle: '@fernandacintra.s',
        followers: '5.7M',
        followers_instagram: 1900000,
        followers_tiktok: 3800000,
        engagement: 3.5,
        engagement_instagram: 2.8,
        engagement_tiktok: 4.2,
        categories: ['Family', 'Parenting', 'Kids'],
        subcategories: ['Maternidade', 'Kids Fashion', 'Educação Infantil'],
        score: 92,
        sollerExclusive: true,
        trending: true,
        avgROI: 4.8,
        price: 42000,
        growth: 14.2,
        audienceQuality: 93,
        contentScore: 91,
        avatar: '👨‍👩‍👧‍👦',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português'],
        bestPostTime: '14h-16h',
        audienceGender: { female: 88, male: 12 },
        audienceAge: { '18-24': 15, '25-34': 52, '35-44': 28, '45+': 5 },
        brandCollabs: ['Pampers', 'Johnson\'s', 'Fisher-Price'],
        specialties: ['Parenting Tips', 'Kids Content', 'Family Activities'],
        platforms: ['Instagram', 'TikTok'],
        bio: 'Compartilhando a jornada da maternidade com dicas e em família'
    },
    {
        id: 23,
        name: 'Carolina Rivkind',
        handle: '@carolinarivkind',
        followers: '21.2K',
        followers_instagram: 13300,
        followers_tiktok: 7900,
        engagement: 4.5,
        engagement_instagram: 4.2,
        engagement_tiktok: 5.1,
        categories: ['Lifestyle', 'Sustainability', 'Minimalism'],
        subcategories: ['Minimalismo', 'Slow Living', 'Sustentabilidade'],
        score: 86,
        sollerExclusive: true,
        trending: false,
        avgROI: 4.8,
        price: 1200,
        growth: 8.5,
        audienceQuality: 88,
        contentScore: 87,
        avatar: '🏠',
        verified: true,
        location: 'Florianópolis, SC',
        languages: ['Português', 'Inglês'],
        bestPostTime: '10h-12h',
        audienceGender: { female: 76, male: 24 },
        audienceAge: { '18-24': 22, '25-34': 48, '35-44': 25, '45+': 5 },
        brandCollabs: ['IKEA', 'Etna', 'Zara Home'],
        specialties: ['Minimalist Living', 'Sustainable Lifestyle', 'Home Organization'],
        platforms: ['Instagram', 'TikTok'],
        bio: 'Estilo de vida com minimalismo, slow living e sustentabilidade'
    },
    {
        id: 24,
        name: 'Ellen Milgrau',
        handle: '@ellenmilgrau',
        followers: '3.6M',
        followers_instagram: 1300000,
        followers_tiktok: 2300000,
        engagement: 2.8,
        engagement_instagram: 2.5,
        engagement_tiktok: 3.2,
        categories: ['Fashion', 'Entertainment'],
        subcategories: ['Fast Fashion', 'Looks do Dia', 'Tendências TikTok'],
        score: 90,
        sollerExclusive: true,
        trending: true,
        avgROI: 4.5,
        price: 32000,
        growth: 9.7,
        audienceQuality: 91,
        contentScore: 89,
        avatar: '👗',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português'],
        bestPostTime: '19h-21h',
        audienceGender: { female: 84, male: 16 },
        audienceAge: { '18-24': 48, '25-34': 35, '35-44': 12, '45+': 5 },
        brandCollabs: ['Shein', 'Zara', 'H&M'],
        specialties: ['Fashion Trends', 'TikTok Content', 'OOTD'],
        platforms: ['Instagram', 'TikTok', 'YouTube'],
        bio: 'As últimas tendências da moda e humor em um só lugar'
    },
    {
        id: 25,
        name: 'Gabriela Morais',
        handle: '@eusougabriela',
        followers: '5.627M',
        followers_instagram: 5600000,
        followers_tiktok: 27200,
        engagement: 1.2,
        engagement_instagram: 1.2,
        engagement_tiktok: 1.5,
        categories: ['Lifestyle', 'Travel', 'Luxury', 'Fashion'],
        score: 88,
        sollerExclusive: true,
        trending: false,
        avgROI: 3.9,
        price: 48000,
        growth: 1.8,
        audienceQuality: 87,
        contentScore: 89,
        avatar: '✈️',
        verified: true,
        location: 'Miami, FL / São Paulo, SP',
        languages: ['Português', 'Inglês', 'Espanhol'],
        bestPostTime: '20h-22h',
        audienceGender: { female: 71, male: 29 },
        audienceAge: { '18-24': 25, '25-34': 45, '35-44': 22, '45+': 8 },
        brandCollabs: ['Dior', 'Four Seasons', 'Emirates'],
        specialties: ['Luxury Travel', 'High Fashion', 'Lifestyle Content'],
        platforms: ['Instagram', 'TikTok'],
        bio: 'Compartilhando um lifestyle de luxo, viagens e alta moda'
    },
    {
        id: 26,
        name: 'Julia Faria',
        handle: '@juliafaria',
        followers: '1.2M',
        followers_instagram: 1200000,
        followers_tiktok: 0,
        engagement: 1.8,
        engagement_instagram: 1.8,
        engagement_tiktok: 0,
        categories: ['Lifestyle', 'Wellness', 'Entrepreneurship'],
        score: 87,
        sollerExclusive: false,
        trending: false,
        avgROI: 4.0,
        price: 22000,
        growth: 2.1,
        audienceQuality: 89,
        contentScore: 88,
        avatar: '🧘‍♀️',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português'],
        bestPostTime: '18h-20h',
        audienceGender: { female: 90, male: 10 },
        audienceAge: { '18-24': 20, '25-34': 45, '35-44': 25, '45+': 10 },
        brandCollabs: ['Adidas', 'L\'Occitane', 'Natura'],
        specialties: ['Self-care', 'Inspirational Content', 'Podcasts'],
        platforms: ['Instagram', 'Twitter', 'Facebook'],
        bio: 'Inspirando autocuidado e bem-estar através da vida real'
    },
    {
        id: 27,
        name: 'Mariana Saad',
        handle: '@marisaad',
        followers: '5.8M',
        followers_instagram: 5800000,
        followers_tiktok: 0,
        engagement: 1.5,
        engagement_instagram: 1.5,
        engagement_tiktok: 0,
        categories: ['Beauty', 'Fashion'],
        score: 92,
        sollerExclusive: false,
        trending: true,
        avgROI: 4.9,
        price: 55000,
        growth: 3.5,
        audienceQuality: 93,
        contentScore: 91,
        avatar: '💄',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português'],
        bestPostTime: '19h-21h',
        audienceGender: { female: 95, male: 5 },
        audienceAge: { '18-24': 40, '25-34': 40, '35-44': 15, '45+': 5 },
        brandCollabs: ['Sephora', 'MAC', 'Loreal'],
        specialties: ['Makeup Tutorials', 'Product Launches', 'Brand Partnerships'],
        platforms: ['Instagram', 'YouTube'],
        bio: 'Tutoriais de maquiagem e dicas de beleza que vão elevar sua confiança'
    },
    {
        id: 28,
        name: 'Niina Secrets',
        handle: '@niinasecrets',
        followers: '10.5M',
        followers_instagram: 9800000,
        followers_tiktok: 700000,
        engagement: 1.3,
        engagement_instagram: 1.2,
        engagement_tiktok: 1.8,
        categories: ['Beauty', 'Lifestyle'],
        score: 93,
        sollerExclusive: false,
        trending: true,
        avgROI: 5.0,
        price: 90000,
        growth: 4.8,
        audienceQuality: 94,
        contentScore: 92,
        avatar: '💖',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português'],
        bestPostTime: '17h-19h',
        audienceGender: { female: 91, male: 9 },
        audienceAge: { '18-24': 38, '25-34': 45, '35-44': 15, '45+': 2 },
        brandCollabs: ['Eudora', 'O Boticário', 'Quem Disse Berenice?'],
        specialties: ['Makeup Reviews', 'Vlogs', 'Beauty Tips'],
        platforms: ['Instagram', 'YouTube'],
        bio: 'Compartilhando segredos de beleza, lifestyle e reviews de produtos'
    },
    {
        id: 29,
        name: 'Thais Carla',
        handle: '@thaiscarla',
        followers: '3.3M',
        followers_instagram: 3300000,
        followers_tiktok: 0,
        engagement: 1.9,
        engagement_instagram: 1.9,
        engagement_tiktok: 0,
        categories: ['Body Positive', 'Fashion', 'Dance'],
        score: 90,
        sollerExclusive: false,
        trending: true,
        avgROI: 4.7,
        price: 35000,
        growth: 6.1,
        audienceQuality: 91,
        contentScore: 89,
        avatar: '💃',
        verified: true,
        location: 'Rio de Janeiro, RJ',
        languages: ['Português'],
        bestPostTime: '20h-22h',
        audienceGender: { female: 92, male: 8 },
        audienceAge: { '18-24': 35, '25-34': 45, '35-44': 15, '45+': 5 },
        brandCollabs: ['Marisa', 'C&A', 'Avon'],
        specialties: ['Body Positivity', 'Dance Content', 'Fashion Inclusiva'],
        platforms: ['Instagram', 'TikTok'],
        bio: 'Celebrando a dança e a moda sem limites. Body positivity em alta'
    },
    {
        id: 30,
        name: 'Mari Maria',
        handle: '@marimaria',
        followers: '21.5M',
        followers_instagram: 20000000,
        followers_tiktok: 1500000,
        engagement: 1.1,
        engagement_instagram: 1.0,
        engagement_tiktok: 1.5,
        categories: ['Beauty', 'Makeup'],
        score: 95,
        sollerExclusive: false,
        trending: true,
        avgROI: 5.5,
        price: 150000,
        growth: 7.8,
        audienceQuality: 95,
        contentScore: 94,
        avatar: '👩‍🎤',
        verified: true,
        location: 'Belo Horizonte, MG',
        languages: ['Português'],
        bestPostTime: '18h-20h',
        audienceGender: { female: 94, male: 6 },
        audienceAge: { '18-24': 45, '25-34': 38, '35-44': 12, '45+': 5 },
        brandCollabs: ['Mari Maria Makeup', 'Sephora', 'MAC'],
        specialties: ['Makeup Tutorials', 'Product Creation', 'Beauty Entrepreneurship'],
        platforms: ['Instagram', 'TikTok', 'YouTube'],
        bio: 'Apaixonada por maquiagem, arte e empreendedorismo'
    },
    {
        id: 31,
        name: 'João Freire',
        handle: '@joaofreire',
        followers: '55K',
        followers_instagram: 50000,
        followers_tiktok: 5000,
        engagement: 3.9,
        engagement_instagram: 3.8,
        engagement_tiktok: 4.2,
        categories: ['Business', 'Technology', 'Startups'],
        score: 88,
        sollerExclusive: false,
        trending: false,
        avgROI: 4.6,
        price: 2800,
        growth: 9.1,
        audienceQuality: 90,
        contentScore: 89,
        avatar: '💻',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português', 'Inglês'],
        bestPostTime: '10h-12h',
        audienceGender: { female: 35, male: 65 },
        audienceAge: { '18-24': 30, '25-34': 50, '35-44': 15, '45+': 5 },
        brandCollabs: ['Nubank', 'Resultados Digitais', 'Conta Azul'],
        specialties: ['Tech Reviews', 'Startup Mentoring', 'Fintech'],
        platforms: ['Instagram', 'TikTok'],
        bio: 'Tech, negócios e o ecossistema de startups na palma da sua mão'
    },
    {
        id: 32,
        name: 'Beatriz Santos',
        handle: '@beatriz.santos',
        followers: '78K',
        followers_instagram: 78000,
        followers_tiktok: 0,
        engagement: 4.1,
        engagement_instagram: 4.1,
        engagement_tiktok: 0,
        categories: ['Art', 'Illustration', 'Creativity'],
        score: 87,
        sollerExclusive: false,
        trending: false,
        avgROI: 4.3,
        price: 2100,
        growth: 6.5,
        audienceQuality: 88,
        contentScore: 91,
        avatar: '🖌️',
        verified: true,
        location: 'Belo Horizonte, MG',
        languages: ['Português'],
        bestPostTime: '15h-17h',
        audienceGender: { female: 70, male: 30 },
        audienceAge: { '18-24': 40, '25-34': 35, '35-44': 18, '45+': 7 },
        brandCollabs: ['Faber-Castell', 'Moleskine', 'Adobe'],
        specialties: ['Digital Art', 'Live Painting', 'Creative Process'],
        platforms: ['Instagram', 'TikTok', 'Kwai'],
        bio: 'Processo criativo, ilustrações e arte digital para inspirar o seu dia'
    },
    {
        id: 33,
        name: 'Ricardo Oliveira',
        handle: '@ricardo_fit',
        followers: '1.2M',
        followers_instagram: 1100000,
        followers_tiktok: 100000,
        engagement: 1.5,
        engagement_instagram: 1.4,
        engagement_tiktok: 1.8,
        categories: ['Fitness', 'Nutrition', 'Sports'],
        score: 89,
        sollerExclusive: false,
        trending: false,
        avgROI: 4.2,
        price: 18000,
        growth: 2.5,
        audienceQuality: 88,
        contentScore: 90,
        avatar: '🏋️‍♂️',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português'],
        bestPostTime: '7h-9h',
        audienceGender: { female: 45, male: 55 },
        audienceAge: { '18-24': 30, '25-34': 40, '35-44': 20, '45+': 10 },
        brandCollabs: ['Smart Fit', 'Probiótica', 'Growth Supplements'],
        specialties: ['Workout Plans', 'Diet Tips', 'Bodybuilding'],
        platforms: ['Instagram', 'TikTok'],
        bio: 'Planos de treino e dicas de nutrição para atingir seu melhor shape'
    },
    {
        id: 34,
        name: 'Sofia Tavares',
        handle: '@sofia_tavares',
        followers: '450K',
        followers_instagram: 420000,
        followers_tiktok: 30000,
        engagement: 2.8,
        engagement_instagram: 2.7,
        engagement_tiktok: 3.2,
        categories: ['Lifestyle', 'Travel', 'Photography'],
        score: 89,
        sollerExclusive: false,
        trending: false,
        avgROI: 4.5,
        price: 8500,
        growth: 4.9,
        audienceQuality: 90,
        contentScore: 90,
        avatar: '📸',
        verified: true,
        location: 'Rio de Janeiro, RJ',
        languages: ['Português', 'Inglês'],
        bestPostTime: '12h-14h',
        audienceGender: { female: 75, male: 25 },
        audienceAge: { '18-24': 28, '25-34': 45, '35-44': 20, '45+': 7 },
        brandCollabs: ['Booking.com', 'TripAdvisor', 'Canon'],
        specialties: ['Travel Vlogs', 'Photo Editing', 'Destination Guides'],
        platforms: ['Instagram', 'TikTok'],
        bio: 'Guias de viagem e fotografia para explorar o mundo de um jeito único'
    },
    {
        id: 35,
        name: 'Lucas Carvalho',
        handle: '@lucascarvalho',
        followers: '85K',
        followers_instagram: 80000,
        followers_tiktok: 5000,
        engagement: 3.5,
        engagement_instagram: 3.4,
        engagement_tiktok: 4.0,
        categories: ['Business', 'Personal Development'],
        score: 87,
        sollerExclusive: false,
        trending: false,
        avgROI: 4.2,
        price: 2500,
        growth: 7.8,
        audienceQuality: 89,
        contentScore: 88,
        avatar: '📈',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português'],
        bestPostTime: '8h-10h',
        audienceGender: { female: 40, male: 60 },
        audienceAge: { '18-24': 25, '25-34': 50, '35-44': 20, '45+': 5 },
        brandCollabs: ['Sebrae', 'Endeavor', 'Coursera'],
        specialties: ['Career Advice', 'Productivity', 'Leadership'],
        platforms: ['Instagram', 'YouTube', 'TikTok'],
        bio: 'Dicas de produtividade profissional para impulsionar sua carreira'
    },
    {
        id: 36,
        name: 'Isabella Rodrigues',
        handle: '@isabella_rod',
        followers: '210K',
        followers_instagram: 200000,
        followers_tiktok: 10000,
        engagement: 2.5,
        engagement_instagram: 2.4,
        engagement_tiktok: 2.8,
        categories: ['Fashion', 'Beauty', 'Minimalism'],
        score: 88,
        sollerExclusive: false,
        trending: false,
        avgROI: 4.1,
        price: 4500,
        growth: 3.1,
        audienceQuality: 89,
        contentScore: 87,
        avatar: '🕊️',
        verified: true,
        location: 'Rio de Janeiro, RJ',
        languages: ['Português'],
        bestPostTime: '11h-13h',
        audienceGender: { female: 88, male: 12 },
        audienceAge: { '18-24': 30, '25-34': 45, '35-44': 20, '45+': 5 },
        brandCollabs: ['Brazzale', 'Basico.com', 'Sallve'],
        specialties: ['Minimalist Fashion', 'Capsule Wardrobe', 'Sustainable Beauty'],
        platforms: ['Instagram', 'TikTok'],
        bio: 'Moda e beleza com uma abordagem minimalista e sustentável'
    },
    {
        id: 37,
        name: 'Felipe Neves',
        handle: '@felipe_neves',
        followers: '35K',
        followers_instagram: 35000,
        followers_tiktok: 0,
        engagement: 5.0,
        engagement_instagram: 5.0,
        engagement_tiktok: 0,
        categories: ['Art', 'Illustration', 'Design'],
        score: 90,
        sollerExclusive: false,
        trending: false,
        avgROI: 4.8,
        price: 1800,
        growth: 8.9,
        audienceQuality: 91,
        contentScore: 92,
        avatar: '🎨',
        verified: true,
        location: 'Curitiba, PR',
        languages: ['Português', 'Inglês'],
        bestPostTime: '19h-21h',
        audienceGender: { female: 55, male: 45 },
        audienceAge: { '18-24': 40, '25-34': 40, '35-44': 15, '45+': 5 },
        brandCollabs: ['Wacom', 'CorelDRAW', 'Behance'],
        specialties: ['Digital Painting', 'Character Design', 'Graphic Design'],
        platforms: ['Instagram', 'TikTok'],
        bio: 'Ilustrações e design para dar vida a novas ideias'
    },
    {
        id: 38,
        name: 'Giovanna Ferrarezi',
        handle: '@giovannaferrarezi',
        followers: '960K',
        followers_instagram: 960000,
        followers_tiktok: 0,
        engagement: 1.8,
        engagement_instagram: 1.8,
        engagement_tiktok: 0,
        categories: ['Lifestyle', 'Fashion', 'Beauty'],
        score: 88,
        sollerExclusive: false,
        trending: false,
        avgROI: 4.0,
        price: 15000,
        growth: 2.3,
        audienceQuality: 89,
        contentScore: 87,
        avatar: '🌟',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português'],
        bestPostTime: '17h-19h',
        audienceGender: { female: 85, male: 15 },
        audienceAge: { '18-24': 30, '25-34': 45, '35-44': 20, '45+': 5 },
        brandCollabs: ['O Boticário', 'Ambev', 'Coca-Cola'],
        specialties: ['Everyday Life', 'OOTD', 'Product Reviews'],
        platforms: ['Instagram', 'YouTube', 'LinkedIn', 'Twitter'],
        bio: 'Um olhar autêntico sobre moda, beleza e o cotidiano'
    },
    {
        id: 39,
        name: 'Luisa Accorsi',
        handle: '@luisaaccorsi',
        followers: '1.5M',
        followers_instagram: 1500000,
        followers_tiktok: 0,
        engagement: 1.6,
        engagement_instagram: 1.6,
        engagement_tiktok: 0,
        categories: ['Fashion', 'Luxury', 'Travel'],
        score: 90,
        sollerExclusive: false,
        trending: false,
        avgROI: 4.3,
        price: 25000,
        growth: 3.5,
        audienceQuality: 91,
        contentScore: 90,
        avatar: '✨',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português', 'Inglês'],
        bestPostTime: '14h-16h',
        audienceGender: { female: 89, male: 11 },
        audienceAge: { '18-24': 25, '25-34': 50, '35-44': 20, '45+': 5 },
        brandCollabs: ['Prada', 'Gucci', 'Chanel'],
        specialties: ['Luxury Fashion', 'High-end Lifestyle', 'Travel Vlogs'],
        platforms: ['Instagram', 'YouTube'],
        bio: 'Um lifestyle elegante com foco em moda, luxo e viagens inesquecíveis'
    },
    {
        id: 40,
        name: 'Isabelle Drummond',
        handle: '@isabelledrummond',
        followers: '2.5M',
        followers_instagram: 2500000,
        followers_tiktok: 0,
        engagement: 1.2,
        engagement_instagram: 1.2,
        engagement_tiktok: 0,
        categories: ['Entertainment', 'Activism', 'Lifestyle'],
        score: 87,
        sollerExclusive: false,
        trending: false,
        avgROI: 3.8,
        price: 30000,
        growth: 1.5,
        audienceQuality: 88,
        contentScore: 88,
        avatar: '🌱',
        verified: true,
        location: 'Rio de Janeiro, RJ',
        languages: ['Português'],
        bestPostTime: '20h-22h',
        audienceGender: { female: 65, male: 35 },
        audienceAge: { '18-24': 20, '25-34': 40, '35-44': 30, '45+': 10 },
        brandCollabs: ['O Boticário', 'Natura', 'Greenpeace'],
        specialties: ['Environmental Causes', 'Vegan Lifestyle', 'Acting'],
        platforms: ['Instagram'],
        bio: 'Uma voz pelo meio ambiente e um olhar artístico sobre a vida'
    },
    {
        id: 41,
        name: 'Felipe Neto',
        handle: '@felipeneto',
        followers: '45M',
        followers_instagram: 17000000,
        followers_tiktok: 13000000,
        engagement: 0.9,
        engagement_instagram: 0.8,
        engagement_tiktok: 1.1,
        categories: ['Entertainment', 'Education', 'Activism'],
        score: 91,
        sollerExclusive: false,
        trending: true,
        avgROI: 4.1,
        price: 250000,
        growth: 2.5,
        audienceQuality: 89,
        contentScore: 92,
        avatar: '🦉',
        verified: true,
        location: 'Rio de Janeiro, RJ',
        languages: ['Português'],
        bestPostTime: '18h-20h',
        audienceGender: { female: 55, male: 45 },
        audienceAge: { '18-24': 55, '25-34': 30, '35-44': 10, '45+': 5 },
        brandCollabs: ['Netflix', 'Coca-Cola', 'iFood'],
        specialties: ['YouTube Content', 'Political Commentary', 'Social Media Trends'],
        platforms: ['YouTube', 'Instagram', 'TikTok', 'Facebook', 'Twitter', 'Twitch'],
        bio: 'Opinião e entretenimento que impulsionam conversas relevantes'
    },
    {
        id: 42,
        name: 'Bianca Andrade',
        handle: '@bianca',
        followers: '20M',
        followers_instagram: 19000000,
        followers_tiktok: 1000000,
        engagement: 1.5,
        engagement_instagram: 1.4,
        engagement_tiktok: 1.8,
        categories: ['Beauty', 'Business', 'Lifestyle'],
        score: 94,
        sollerExclusive: false,
        trending: true,
        avgROI: 5.2,
        price: 120000,
        growth: 6.0,
        audienceQuality: 93,
        contentScore: 93,
        avatar: ' boca',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português'],
        bestPostTime: '21h-23h',
        audienceGender: { female: 93, male: 7 },
        audienceAge: { '18-24': 45, '25-34': 40, '35-44': 10, '45+': 5 },
        brandCollabs: ['Boca Rosa Beauty', 'Eudora', 'Avon'],
        specialties: ['Makeup Entrepreneurship', 'Business Strategy', 'Beauty Tutorials'],
        platforms: ['Instagram', 'TikTok', 'YouTube'],
        bio: 'De criadora de conteúdo a empresária de sucesso na indústria da beleza'
    },
    {
        id: 43,
        name: 'Gkay',
        handle: '@gessicakayane',
        followers: '21M',
        followers_instagram: 20000000,
        followers_tiktok: 1000000,
        engagement: 1.3,
        engagement_instagram: 1.2,
        engagement_tiktok: 1.5,
        categories: ['Entertainment', 'Comedy', 'Lifestyle'],
        score: 90,
        sollerExclusive: false,
        trending: true,
        avgROI: 4.5,
        price: 110000,
        growth: 3.8,
        audienceQuality: 88,
        contentScore: 91,
        avatar: '😂',
        verified: true,
        location: 'São Paulo, SP',
        languages: ['Português'],
        bestPostTime: '22h-00h',
        audienceGender: { female: 65, male: 35 },
        audienceAge: { '18-24': 40, '25-34': 35, '35-44': 15, '45+': 10 },
        brandCollabs: ['Farofa da Gkay', 'Netflix', 'Buser'],
        specialties: ['Humor', 'Events Production', 'TikTok Trends'],
        platforms: ['Instagram', 'TikTok', 'YouTube', 'Twitter'],
        bio: 'Humor e entretenimento que quebram a internet'
    },
    {
        id: 44,
        name: 'Virginia Fonseca',
        handle: '@virginia',
        followers: '43.2M',
        followers_instagram: 42000000,
        followers_tiktok: 1200000,
        engagement: 1.8,
        engagement_instagram: 1.7,
        engagement_tiktok: 2.0,
        categories: ['Beauty', 'Family', 'Lifestyle'],
        score: 95,
        sollerExclusive: false,
        trending: true,
        avgROI: 6.0,
        price: 200000,
        growth: 9.5,
        audienceQuality: 94,
        contentScore: 95,
        avatar: '👸',
        verified: true,
        location: 'Goiânia, GO',
        languages: ['Português'],
        bestPostTime: '19h-21h',
        audienceGender: { female: 95, male: 5 },
        audienceAge: { '18-24': 50, '25-34': 40, '35-44': 8, '45+': 2 },
        brandCollabs: ['WePink', 'Magazine Luiza', 'Coca-Cola'],
        specialties: ['Family Life', 'Product Launches', 'Beauty Entrepreneurship'],
        platforms: ['Instagram', 'TikTok', 'YouTube'],
        bio: 'O lifestyle de uma mãe e empreendedora no universo da beleza'
    },
    {
        id: 45,
        name: 'Casimiro',
        handle: '@casimiro',
        followers: '9.8M',
        followers_instagram: 5500000,
        followers_tiktok: 4300000,
        engagement: 2.5,
        engagement_instagram: 2.0,
        engagement_tiktok: 3.2,
        categories: ['Entertainment', 'Sports', 'Gaming'],
        score: 92,
        sollerExclusive: false,
        trending: true,
        avgROI: 4.8,
        price: 85000,
        growth: 10.2,
        audienceQuality: 91,
        contentScore: 93,
        avatar: '⚽',
        verified: true,
        location: 'Rio de Janeiro, RJ',
        languages: ['Português'],
        bestPostTime: '22h-00h',
        audienceGender: { female: 30, male: 70 },
        audienceAge: { '18-24': 60, '25-34': 30, '35-44': 8, '45+': 2 },
        brandCollabs: ['Twitch', 'YouTube', 'Coca-Cola'],
        specialties: ['Live Commentary', 'Sports Analysis', 'Gaming'],
        platforms: ['Twitch', 'YouTube', 'Instagram', 'TikTok', 'Twitter'],
        bio: 'Onde o esporte, o humor e o gaming se encontram em transmissões ao vivo'
    },
    {
        id: 46,
        name: 'Nath Finanças',
        handle: '@nathaliaarcuri',
        followers: '3.1M',
        followers_instagram: 1800000,
        followers_tiktok: 1300000,
        engagement: 2.1,
        engagement_instagram: 2.0,
        engagement_tiktok: 2.3,
        categories: ['Business', 'Finance', 'Education'],
        score: 90,
        sollerExclusive: false,
        trending: false,
        avgROI: 4.7,
        price: 38000,
        growth: 7.5,
        audienceQuality: 92,
        contentScore: 90,
        avatar: '💰',
        verified: true,
        location: 'Rio de Janeiro, RJ',
        languages: ['Português'],
        bestPostTime: '19h-21h',
        audienceGender: { female: 60, male: 40 },
        audienceAge: { '18-24': 30, '25-34': 45, '35-44': 20, '45+': 5 },
        brandCollabs: ['NuInvest', 'Magnetis', 'C6 Bank'],
        specialties: ['Financial Education', 'Personal Finance', 'Investment Tips'],
        platforms: ['YouTube', 'Instagram', 'TikTok'],
        bio: 'Educação financeira para todos, de forma simples e direta'
    },
    {
        id: 47,
        name: 'Jout Jout',
        handle: '@joutjout',
        followers: '1.2M',
        followers_instagram: 1200000,
        followers_tiktok: 0,
        engagement: 1.8,
        engagement_instagram: 1.8,
        engagement_tiktok: 0,
        categories: ['Lifestyle', 'Mental Health', 'Art'],
        score: 88,
        sollerExclusive: false,
        trending: false,
        avgROI: 4.2,
        price: 22000,
        growth: 1.5,
        audienceQuality: 89,
        contentScore: 91,
        avatar: '🧠',
        verified: true,
        location: 'Rio de Janeiro, RJ',
        languages: ['Português'],
        bestPostTime: '20h-22h',
        audienceGender: { female: 75, male: 25 },
        audienceAge: { '18-24': 35, '25-34': 40, '35-44': 20, '45+': 5 },
        brandCollabs: ['Faber-Castell', 'Natura', 'TEDx'],
        specialties: ['Mental Health', 'Self-Love', 'Essay Content'],
        platforms: ['YouTube', 'Instagram', 'Facebook'],
        bio: 'Reflexões sobre a vida e a saúde mental com um toque de leveza e arte'
    },
    {
        id: 48,
        name: 'Gil do Vigor',
        handle: '@gildovigor',
        followers: '14.5M',
        followers_instagram: 14000000,
        followers_tiktok: 500000,
        engagement: 1.5,
        engagement_instagram: 1.4,
        engagement_tiktok: 1.8,
        categories: ['Education', 'Entertainment', 'Finance'],
        score: 91,
        sollerExclusive: false,
        trending: true,
        avgROI: 4.6,
        price: 95000,
        growth: 5.0,
        audienceQuality: 90,
        contentScore: 92,
        avatar: '🎓',
        verified: true,
        location: 'Recife, PE',
        languages: ['Português'],
        bestPostTime: '20h-22h',
        audienceGender: { female: 55, male: 45 },
        audienceAge: { '18-24': 45, '25-34': 35, '35-44': 15, '45+': 5 },
        brandCollabs: ['O Boticário', 'Vigor', 'Banco do Brasil'],
        specialties: ['Economics', 'Public Speaking', 'Social Activism'],
        platforms: ['Instagram', 'Twitter', 'TikTok'],
        bio: 'Economia, entretenimento e o vigor que transforma o Brasil'
    }
];

// ===== MARKETPLACE METRICS & BENCHMARKS =====
const marketplaceBenchmarks = {
    avgEngagementRate: {
        micro: 3.5,
        mid: 2.2,
        macro: 1.5,
        mega: 0.8
    },
    avgROI: {
        beauty: 4.8,
        fashion: 4.2,
        lifestyle: 4.1,
        fitness: 4.5,
        business: 4.3,
        entertainment: 3.7,
        family: 4.6
    },
    avgPriceRange: {
        micro: { min: 500, max: 5000 },
        mid: { min: 5000, max: 20000 },
        macro: { min: 20000, max: 50000 },
        mega: { min: 50000, max: 250000 }
    },
    platformDistribution: {
        instagram: 68,
        tiktok: 22,
        youtube: 7,
        twitter: 3
    }
};

// ===== CAMPAIGN TEMPLATES =====
const campaignTemplates = [
    {
        id: 1,
        name: 'Lançamento de Produto',
        duration: '30 dias',
        deliverables: ['3 posts feed', '10 stories', '1 reels'],
        estimatedROI: 4.2,
        recommendedBudget: { min: 20000, max: 50000 },
        categories: ['Beauty', 'Fashion', 'Tech']
    },
    {
        id: 2,
        name: 'Brand Awareness',
        duration: '60 dias',
        deliverables: ['5 posts feed', '20 stories', '2 reels', '1 IGTV'],
        estimatedROI: 3.8,
        recommendedBudget: { min: 50000, max: 100000 },
        categories: ['Lifestyle', 'Fashion', 'Food']
    },
    {
        id: 3,
        name: 'Conversão e Vendas',
        duration: '15 dias',
        deliverables: ['2 posts feed', '15 stories com swipe up', '1 live'],
        estimatedROI: 5.2,
        recommendedBudget: { min: 15000, max: 35000 },
        categories: ['Beauty', 'Fashion', 'Fitness']
    },
    {
        id: 4,
        name: 'Embaixador de Marca',
        duration: '180 dias',
        deliverables: ['12 posts feed', 'Stories semanais', '4 reels', 'Eventos'],
        estimatedROI: 4.8,
        recommendedBudget: { min: 100000, max: 500000 },
        categories: ['All']
    }
];

// ===== BRAND PARTNERS =====
const brandPartners = [
    { name: 'Natura', campaigns: 23, totalInvestment: 2800000, avgROI: 4.2 },
    { name: 'O Boticário', campaigns: 19, totalInvestment: 2200000, avgROI: 3.8 },
    { name: 'Magazine Luiza', campaigns: 31, totalInvestment: 3500000, avgROI: 5.1 },
    { name: 'Americanas', campaigns: 27, totalInvestment: 2900000, avgROI: 4.5 },
    { name: 'Nike', campaigns: 15, totalInvestment: 4200000, avgROI: 3.9 },
    { name: 'Adidas', campaigns: 12, totalInvestment: 3100000, avgROI: 3.7 },
    { name: 'Zara', campaigns: 18, totalInvestment: 2600000, avgROI: 4.3 },
    { name: 'C&A', campaigns: 22, totalInvestment: 1900000, avgROI: 4.6 },
    { name: 'Renner', campaigns: 20, totalInvestment: 2100000, avgROI: 4.4 },
    { name: 'Samsung', campaigns: 8, totalInvestment: 5800000, avgROI: 3.5 }
];

// ===== TRENDING TOPICS & HASHTAGS =====
const trendingTopics = [
    { hashtag: '#sustentabilidade', posts: '2.8M', growth: 450, category: 'Lifestyle' },
    { hashtag: '#skincare', posts: '4.2M', growth: 320, category: 'Beauty' },
    { hashtag: '#fitness', posts: '3.5M', growth: 280, category: 'Fitness' },
    { hashtag: '#moda2025', posts: '1.9M', growth: 210, category: 'Fashion' },
    { hashtag: '#maternidade', posts: '2.1M', growth: 180, category: 'Family' },
    { hashtag: '#empreendedorismo', posts: '1.5M', growth: 150, category: 'Business' }
];

// ===== EXPORT FUNCTIONS =====
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        influencers,
        marketplaceBenchmarks,
        campaignTemplates,
        brandPartners,
        trendingTopics
    };
}